/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_salvador_macias;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Apple
 */
public class NelbixOs extends javax.swing.JFrame {

    /**
     * Creates new form NelbixOs
     */
    public NelbixOs() throws IOException {
        initComponents();
        jTextArea1.setEditable(false);
        //   File file = new File("'/Users/Apple/NetBeansProjects/Lab9p2_salvador_macias/nelbix_root:.'", "nelbix_root/.");
        // file.createNewFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jla = new javax.swing.JLabel();
        txt_comandos = new javax.swing.JTextField();
        jla1 = new javax.swing.JLabel();
        txt_NombreArchivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nelbix - terminal grafica");

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(102, 255, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("Nelbix v1.0 - Bienvenido a la terminal grafica\n");
        jScrollPane1.setViewportView(jTextArea1);

        jla.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jla.setText("Comando: ");

        txt_comandos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_comandosActionPerformed(evt);
            }
        });

        jla1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jla1.setText("Nombre de archivo: ");

        txt_NombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jla, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_comandos, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jla1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_comandos)
                            .addComponent(jla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_NombreArchivo))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_comandosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_comandosActionPerformed

        if (txt_comandos.getText().equals("exit")) {
            System.exit(0);
        } else if (txt_comandos.getText().equals("ls")) {
            File raiz = new File("'/Users/Apple/NetBeansProjects/Lab9p2_salvador_macias/nelbix_root:.'");
            File[] archivos = raiz.listFiles((dir, nombre) -> nombre.toLowerCase().endsWith(".txt"));
            if (archivos.length == 0 ) {

                jTextArea1.setText("(no hay archivos)");

            } else {
                for (File archivo : archivos) {
                    jTextArea1.append(archivo.getName() + "\n");

                }
            }
        } else if (txt_comandos.getText().contains("touch")) {
            File nuevo = new File("'/Users/Apple/NetBeansProjects/Lab9p2_salvador_macias/nelbix_root:.'", txt_NombreArchivo.getText());
            try {
                nuevo.createNewFile();
                jTextArea1.setText("archivo " + txt_NombreArchivo.getText() + " creado");
            } catch (IOException ex) {
                Logger.getLogger(NelbixOs.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (txt_comandos.getText().contains("cat")) {
            jTextArea1.setText("auxilio");

        } else if (txt_comandos.getText().contains("echo")) {
            jTextArea1.setText("texto sobrescrito");

        } else if (txt_comandos.getText().contains(">>>")) {
            jTextArea1.setText("texto agregado");

        } else if (txt_comandos.getText().equals("rm")) {
            jTextArea1.setText("archivo eliminado");
        } else if (txt_comandos.getText().equals("clear")) {
            jTextArea1.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "el comando ingresado no es valido", "error", HEIGHT);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_comandosActionPerformed

    private void txt_NombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NelbixOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NelbixOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NelbixOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NelbixOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NelbixOs().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NelbixOs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jla;
    private javax.swing.JLabel jla1;
    private javax.swing.JTextField txt_NombreArchivo;
    private javax.swing.JTextField txt_comandos;
    // End of variables declaration//GEN-END:variables
}
